mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=feature_2
    - MYSQL_PASSWORD=petclinic123
    - MYSQL_DATABASE=petclinic456
  volumes:
    - "./conf.d:/etc/mysql/conf.d:rw"
